name: Publish to Chrome Web Store with Release Notes

on:
  push:
    branches:
      - main

jobs:
  update-version-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Auto-Increment Version in manifest.json
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          IFS='.' read -r major minor patch <<< "$VERSION"
          NEW_VERSION="$major.$minor.$(($patch + 1))"
          jq --arg new_version "$NEW_VERSION" '.version=$new_version' manifest.json > temp.json && mv temp.json manifest.json
          echo "New version: $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit Updated manifest.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add manifest.json
          git commit -m "Auto-incremented version to ${{ env.VERSION }}"
          git push

      - name: Generate Release Notes
        id: release_notes
        run: |
          echo "## Release Notes for v${{ env.VERSION }}" > release_notes.md
          echo "" >> release_notes.md
          git log --pretty=format:"- %s (%an)" -n 10 >> release_notes.md
          cat release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.VERSION }}
          name: "Version ${{ env.VERSION }}"
          body_path: release_notes.md

      - name: Zip the Extension Files
        run: |
          zip -r extension.zip * -x "*.git*" ".github/*"

      - name: Upload to Chrome Web Store
        run: |
          curl -X PUT -H "Authorization: Bearer ${{ secrets.CHROME_ACCESS_TOKEN }}" \
               -H "x-goog-api-version: 2" \
               -T extension.zip \
               "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${{ secrets.YOUR_APP_ID }}"

      - name: Publish the Extension with Release Notes
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.CHROME_ACCESS_TOKEN }}" \
               -H "x-goog-api-version: 2" \
               -H "Content-Type: application/json" \
               -d '{
                  "target": "default",
                  "notes": "'"$(cat release_notes.md | sed ':a;N;$!ba;s/\n/\\n/g')"'" 
               }' \
               "https://www.googleapis.com/chromewebstore/v1.1/items/${{ secrets.YOUR_APP_ID }}/publish"
